### ISSUE TITLE
[JOSS Review] - Suggestion for tutorial documentation

### ISSUE THREAD

**Issue by ericfell** [mxwalbert/cohesivm#4]
Dear authors,

The five _implement.../...workflow_ tutorials provided are well documented, but I feel that the tutorial section could benefit from a few initial sentences of high-level description of an example of a device a user would want to connect, and the subsequent experiment they'd perform. 
This could be described with mentions to `Channel/Device/Interface/Experiment/Measurement` modules and subsequently, `Analysis`. This high-level-example description could be included in the README and the JOSS paper. I feel this would really tie all the tutorials together.

This issue is related to openjournals/joss-reviews#7291

**Comment by mxwalbert** [comment]
Dear @ericfell,
thank you for this suggestion. We added a high-level description in the form of a real-world example, linked it in the README, and summarized it in the JOSS paper: https://github.com/mxwalbert/cohesivm/commit/fe513013142303ca911340f9b52389a0acd19a29
As you predicted, this really ties everything together and makes it more clear how and why one would use the package.
Please let us know if this turned out as expected.

**Comment by ericfell** [comment]
Looks good.
I'll close this issue.
