### ISSUE TITLE
[JOSS Review] - Interface motivation, docs/JOSS paper

### ISSUE THREAD

**Issue by ericfell** [mxwalbert/cohesivm#6]
Dear authors,

The `Interface` module inherently requires an array of electrode contacts (e.g. the MA8X8 array which you've open sourced). I think that `COHESIVM`'s requirement that a device must specifically be an electrode contact array configuration should be **explicitly** stated early on in both the root `README` and the JOSS paper, as this isn't made clear.

The `README`'s listed **Key Features** of _contacting interfaces (`Interface`)... are abstracted into interchangeable units_ is not readily apparent, given the above requirement.

Furthermore, the only interface provided (the in-house MA8X8) appears very specific to your lab. Without more provided examples of interfaces, realistically how applicable is COHESIVM to other groups? Or should this package be refactored specifically as a use case for your specific interface?

I understand my issue seems vague... I totally agree that a modular architecture built of abstract interchangeable units enables flexibility in designing a new system, but the description of the architecture must involve concrete examples to fully motivate its use. I'll add that there is overlap in my comments here and those of enricgrau in the JOSS review thread.

This issue is related to openjournals/joss-reviews#7291

**Comment by mxwalbert** [comment]
Dear @ericfell,

we deliberately designed the package to be reusable and I think refactoring it to a specific use case would make it less applicable to other groups. 

Regarding the ``Interface`` component, I still consider it _interchangeable units_ since this can practically be anything as long as it somehow changes the contact position (which is something you would need if you want to measure combinatorial samples). Do you think it would help to implement a manual contact interface? This ``Interface`` could pause the ``Experiment`` to allow the user to physically change the contact position (e.g., by rewiring) before running the next ``Measurement``.

We added links for the implementation tutorials and for the MA8X8 description in the README, to make them more visible.

We also addressed the comments of @enricgrau regarding the JOSS paper in this issue:
- formulated explicit key features and advantages
- described a practical example for clarifying the usage of the package
- included author contributions

Please let us know if this contributes to resolving your issues and how we should proceed.

**Comment by enricgrau** [comment]
@mxwalbert please update the manuscript.

**Comment by ericfell** [comment]
Looks good from my end.

**Comment by mxwalbert** [comment]
Dear @enricgrau, 
please confirm if you are fine with the paper now and close the issue.

**Comment by enricgrau** [comment]
Looks good to me now @mxwalbert
